mz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mz.views.home', name='home'),
    # url(r'^mz/', include('mz.foo.urls')),
    url(r'^',include('login.urls',namespace='login')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/',include('courses.urls',namespace='courses')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^rewards/',include('rewards.urls',namespace='rewards')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

rewards/urls.py
from django.conf.urls import patterns, url
from rewards import views

urlpatterns = patterns('',
    url(r'^reward/$', views.reward, name="reward"),
    url(r'^rewards/$', views.rewards, name="rewards"),
    url(r'^create/$', views.rewardcreate, name="rewardcreate"),
    url(r'^addReward/$', views.addReward, name="addReward"),
    url(r'^the/(.+)$', views.thereward, name="thereward"),
    url(r'^success/$', views.success, name="success"),
    url(r'^addreview/$', views.addreview, name="addreview"),
    url(r'^uncover/$', views.uncover, name="uncover"),

    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/sun/Dropbox/mz/templates/public/css' } 
	),
	url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/sun/Dropbox/mz/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/sun/Dropbox/mz/templates/public/fonts' } 
    ), 
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^publish/$', views.publish, name="publish"),
    url(r'^setting/$', views.setting, name="setting"),
    url(r'^good/$', views.good, name="good"),
    url(r'^cogood/$', views.cogood, name="cogood"),
    url(r'^get/$', views.getimg, name="get"),
    url(r'^add/$', views.add, name="add"),
    url(r'^share/$', views.share, name="share"),
    url(r'^setting/update/$', views.update, name="update"),
    url(r'^setting/pwdchange/$', views.pwdchange, name="pwdchange"),
    url(r'^setting/head/$', views.head, name="head"),
    url(r'^mycourse/$', views.mycourseact, name="mycourseact"),
    url(r'^home/(.+)$', views.home, name="home"),
    url(r'^message/$', views.message, name="message"),
    url(r'^manage/course/$', views.managecourse, name="managecourse"),
    url(r'^manage/group/$', views.managegroup, name="managegroup"),
    url(r'^manage/reward/$', views.managereward, name="managereward"),
    url(r'^mytopic/$', views.mytopic, name="mytopic"),
    url(r'^teacherapply/$', views.teacherapply, name="teacherapply"),
    url(r'^comment/$', views.comment, name="comment"),
    url(r'^cocomment/$', views.cocomment, name="cocomment"),
    url(r'^get_more_re/$', views.get_more_re, name="get_more_re"),
    
    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/css' } 
	),
	url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/fonts' } 
    ), 
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/img' } 
    ), 
    url(r'^news/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/news' } 
    ), 
    url(r'^ico/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/ico' } 
    ), 
    url(r'^group/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/image' } 
    ), 
)

rewards/models.py
from django.db import models
from courses.models import Types

class Reward(models.Model):
	types=models.ForeignKey(Types)
	from_id=models.IntegerField()
	to=models.IntegerField(blank=True,null=True)
	message_con=models.IntegerField(default=0)
	uncover_con=models.IntegerField(default=0)
	course_id=models.IntegerField()
	name=models.CharField(max_length=199)
	introduce=models.TextField()
	time=models.DateTimeField(auto_now_add=True)
	deadline=models.DateTimeField(auto_now_add=True)
	price=models.FloatField()
	
class Uncover(models.Model):
	reward=models.ForeignKey(Reward)
	to=models.IntegerField()
	time=models.DateTimeField(auto_now_add=True)
	status=models.IntegerField(default=1)

class Reward_mes(models.Model):
	reward=models.ForeignKey(Reward)
	from_id=models.IntegerField()
	content=models.TextField()
	time=models.DateTimeField(auto_now_add=True)
 

rewards/views.py
#encoding:utf-8

from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import PageNotAnInteger, Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render
from rewards.models import Reward,Uncover,Reward_mes
from courses.models import Types,Tiny_type,Course,Lession,Course_comment
from users.models import Info,Teacher,News,Review_of_news,Message,Follow_topic,Follow_user,Follow_group,Follow_course,Post_reward,Post_course,Purchase,Good_news,Good_review_of_news
from django.utils import timezone
import re,md5,os,time,random,base64

def reward(request):
	types=Types.objects.all()
	rewardTable=Reward.objects.all().order_by('-time')
	rewards=[]
	for r in rewardTable:
		areward=[]
		i=Info.objects.get(user_id=r.from_id)
		areward.append(i.img)			#0
		areward.append(r.id)			#1
		areward.append(r.name)		#2
		areward.append(r.price)		#3
		intro=r.introduce[0:70]
		intro=intro+'...'
		areward.append(intro)			#4
		typesTable=Types.objects.get(id=r.types_id)
		areward.append(typesTable.name)	#5
		areward.append(i.domain)		#6
		rewards.append(areward)
	paginator = Paginator(rewards, 15)
	page = request.GET.get('page')
	try:
	    rewards = paginator.page(page)
	except PageNotAnInteger:
	    rewards = paginator.page(1)
	except EmptyPage:
	    rewards = paginator.page(paginator.num_pages)
	result=[]
	info=Info.objects.get(user_id=request.session['id'])
	return render(request,'rewards/rewards.html',{'rewards':rewards,'types':types,'info':info})



def rewards(request):
	if 'order' in request.GET:
		order=int(request.GET['order'])
	else:
		order=0

	if 'typeid' in request.GET:
		typeid=int(request.GET['typeid'])
	else:
		typeid=0
	
	types=Types.objects.all()

	if typeid==0:
		if order==4:
			rewardTable=Reward.objects.all().order_by('price')
		elif order==3:
			rewardTable=Reward.objects.all().order_by('-price')
		elif order==2:
			rewardTable=Reward.objects.all().order_by('-message_con')
		else:
			rewardTable=Reward.objects.all().order_by('-time')
	else:
		if order==4:
			rewardTable=Reward.objects.filter(types_id=int(typeid)).order_by('price')
		elif order==3:
			rewardTable=Reward.objects.filter(types_id=int(typeid)).order_by('-price')
		elif order==2:
			rewardTable=Reward.objects.filter(types_id=int(typeid)).order_by('-message_con')
		else:
			rewardTable=Reward.objects.filter(types_id=int(typeid)).order_by('-time')


	rewards=[]
	for r in rewardTable:
		areward=[]
		i=Info.objects.get(user_id=r.from_id)
		areward.append(i.img)		#0
		areward.append(r.id)			#1
		areward.append(r.name)		#2
		areward.append(r.price)		#3
		intro=r.introduce[0:70]
		intro=intro+'...'
		areward.append(intro)			#4
		typesTable=Types.objects.get(id=r.types_id)
		areward.append(typesTable.name)	#5
		areward.append(i.domain)		#6	
		rewards.append(areward)
	paginator = Paginator(rewards, 15)
	page = request.GET.get('page')
	try:
	    rewards = paginator.page(page)
	except PageNotAnInteger:
	    rewards = paginator.page(1)
	except EmptyPage:
	    rewards = paginator.page(paginator.num_pages)
	result=[]
	info=Info.objects.get(user_id=request.session['id'])
	return render(request,'rewards/rewards.html',{'rewards':rewards,'types':types,'order':order,'typeid':typeid,'info':info})



def rewardcreate(request):
	info=Info.objects.get(user_id=request.session['id'])
	user_name=info.user_name
	user_img=info.img
	types=Types.objects.all()
	rewardscount=Reward.objects.filter(from_id=request.session['id']).count()

	return render(request,'rewards/rewardCreate.html',{'info':info,'types':types,'user_name':user_name,'user_img':user_img,'user_id':request.session['id'],'rewardscount':rewardscount})

def addReward(request):
	course_name=request.POST['course_name']
	course_intro=request.POST['course_intro']
	price=request.POST['price']
	belongtype=request.POST['belongtype']
	reward=Reward(types_id=request.POST['belongtype'],from_id=request.session['id'],name=request.POST['course_name'],introduce=request.POST['course_intro'],price=request.POST['price'],course_id=0)
	reward.save()
	reward.deadline_str=str(reward.deadline)
	reward_list=reward.deadline_str.split('.')
	deadline_str=reward_list[0]
	timeArray=time.strptime(deadline_str,"%Y-%m-%d %H:%M:%S")
	timeStamp=int(time.mktime(timeArray))
	x = time.localtime(timeStamp+2592000)
	reward.deadline=time.strftime('%Y-%m-%d %H:%M:%S',x)
	reward.save()

	return HttpResponseRedirect('../success/?course_name='+course_name+'&reward_id='+str(reward.id))

def success(request):
	course_name=request.GET['course_name']
	reward_id=int(request.GET['reward_id'])
	return render(request,'rewards/success.html',{'course_name':course_name,'reward_id':reward_id})


def thereward(request,id):
	thereward=Reward.objects.get(id=id)
	info=Info.objects.get(user_id=thereward.from_id)
	areward=[]
	areward.append(thereward.name)		#0
	areward.append(thereward.introduce)		#1
	areward.append(thereward.time)		#2
	areward.append(thereward.deadline)		#3
	areward.append(thereward.price)		#4
	areward.append(info.user_name)		#5
	areward.append(info.img)			#6
	Rcount = Reward.objects.filter(from_id=info.user_id).count()
	areward.append(Rcount)				#7
	SUCRcount = Reward.objects.filter(from_id=info.user_id).filter(to__isnull=False).count()
	areward.append(SUCRcount)			#8
	typesTable=Types.objects.get(id=thereward.types_id)
	areward.append(typesTable.name)			#9
	areward.append(id)					#10
	areward.append(info.domain)					#11

	re_rewardTable=Reward_mes.objects.filter(reward_id=id).order_by('-time')
	re_rewards=[]
	for r in re_rewardTable:
		a_re_reward=[]
		info=Info.objects.get(user_id=r.from_id)
		a_re_reward.append(info.img)			#0
		a_re_reward.append(info.user_name)		#1
		a_re_reward.append(r.content)			#2
		a_re_reward.append(r.time)			#3
		a_re_reward.append(r.from_id)			#4
		a_re_reward.append(info.domain)		#5
		re_rewards.append(a_re_reward)
	if Uncover.objects.filter(reward_id=id).filter(to=request.session['id']):
		uncover_exist=1
	else:
		uncover_exist=0
	yellow_stars=range(0,info.credit)
	hollow_stars=range(0,(5-info.credit))
	info=Info.objects.get(user_id=request.session['id'])
	enreward=base64.encodestring(str(thereward.id))
	enuser=base64.encodestring(str(request.session['id']))
	ento=base64.encodestring(str(thereward.from_id))
	return render(request,'rewards/theReward.html',{'enreward':enreward,'enuser':enuser,'ento':ento,'areward':areward,'info':info,'re_rewards':re_rewards,'yellow_stars':yellow_stars,'hollow_stars':hollow_stars,'uncover_exist':uncover_exist})


def addreview(request):
	content=request.GET['content']
	reward_id=request.GET['reward_id']
	from_id=request.session['id']
	re_reward=Reward_mes(reward_id=reward_id,from_id=from_id,content=content)
	re_reward.save()
	info=Info.objects.get(user_id=from_id)
	
	return HttpResponse(str(info.img)+','+str(info.user_name)+','+str(from_id)+','+str(info.domain))



def uncover(request):
	reward_id=request.GET['reward_id']

	uncoverTable=Uncover(reward_id=reward_id,to=request.session['id'],status=1)
	uncoverTable.save()

	rewardTable=Reward.objects.get(id=reward_id)
	rewardTable.uncover_con=int(rewardTable.uncover_con)+1
	rewardTable.save()
	
	
	return HttpResponse(1)

templates/rewards/rewardCreate.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>麦知网——学问有余，乐为人师</title>

<!-- Bootstrap core CSS -->
<link href="../../css/bootstrap.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="../../css/non-responsive.css" rel="stylesheet">

<link href="../../css/courseCreate.css" rel="stylesheet">    
 
 
 
 	
	
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="../js/jquery.min.js"></script>
	
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="../js/bootstrap.js"></script>
		
	<script type="text/javascript">
	function change_list(a)
	{
		$("#case1").css("display","none");
		$("#case2").css("display","none");
		$("#case3").css("display","none");
		$("#case4").css("display","none");
		$("#a1").attr("class","list-group-item");
		$("#a2").attr("class","list-group-item");
		$("#a3").attr("class","list-group-item");
		$("#a4").attr("class","list-group-item");
		$("#case"+a).css("display","block");
		$("#a"+a).attr("class","active list-group-item");
	}




	function typeLabels(a)
	{
		var textvalue=$("#textvalue").val();
		$(".typeLabel3"+a).attr("class","typeLabel1"+a);
		var typeLabel1=$(".typeLabel1"+a);
		var typeLabel2=$(".typeLabel2"+a);
		typeLabel1.css("background-color","#D0D1E6");
		typeLabel2.css("background-color","#F2F2F2");
		typeLabel2.attr("class","typeLabel3"+a);
		typeLabel1.attr("class","typeLabel2"+a);
	//第一次点击 加上这个分类名
		if($('.typeLabel2'+a+'>a').html())
		{
			$("#textvalue").val(textvalue+$('.typeLabel2'+a+'>a').html());
		}
	//第二次点击 减去这个分类名
		if($('.typeLabel3'+a+'>a').html())
		{
			var strPosition=textvalue.indexOf($('.typeLabel3'+a+'>a').html());
			var textNew1=textvalue.substr(0,strPosition);
			var textNew2=textvalue.substr(strPosition+$('.typeLabel3'+a+'>a').html().length,textvalue.length);
			//var textjiechu=textvalue.substr(strPosition,strPosition+$('.typeLabel3'+a+'>#a').html().length);
			var textNew=textNew1+textNew2;
			$("#textvalue").val(textNew);
		}
	}


	function sub()
	{
		$("#subbutton3").attr("id","subbutton1");
		$("#subbutton2").removeAttr("disabled");
		$("#subbutton1").attr("disabled","disabled");
		$("#subbutton2").attr("id","subbutton3");
		$("#subbutton1").attr("id","subbutton2");
	}
		
		
	</script>
</head>
<body>
	{% include 'public/common/header.html' %}
	<div class="container" style="margin-top:45px">
		<div class="row">
<!-- left div -->
			<div class="col-xs-8">
				<div>
					<div class="publisher_img pull-left">
						<img src="{{info.domain}}/{{info.img}}" width="100%" class="img-circle"/>
					</div>
					<div class="publisher_name pull-left">
						<div class="cc_title"><b>创建{{user_name}}的悬赏</b></div>
						<div class="publisher_sign"><i>{{user_name}}一共创建了{{rewardscount}}条悬赏</i></div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div>
					<div class="topdirection"></div>
					<div class="group_mes">
					<form action="{% url 'rewards:addReward' %}" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="group_form_all">
							<div class="group_form_name pull-left"> 求购课程名 </div>
							<div class="group_form pull-left"><input type="text" name="course_name" class="form-control"></div>
							<div class="clearfix"></div>
						</div>
						<div class="group_form_all">
							<div class="group_form_name pull-left"> 求购课程描述 </div>
							<div class="group_form pull-left"><textarea name="course_intro" class="form-control group_textarea"></textarea></div>
							<div class="clearfix"></div>
						</div>
						<div class="group_form_all">
							<div class="group_form_name pull-left"> 悬赏金额 </div>
							<div class="group_form pull-left">
								<div class="input-group">
								  <span class="input-group-addon">￥</span>
								  <input type="text" name="price" class="form-control">
								  <span class="input-group-addon">.00</span>
								</div>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="group_form_all">
<!-- 标签设置  -->	
							<div class="right case4" id="case4">
								<div class="group_form_all">
									<div class="group_form_name pull-left"> 课程分类 </div>
									<div class="group_form pull-left">
										<select name="belongtype" class="form-control">
<!-- 循环显示分类标签 开始处 -->{% for t in types %}
											<option value="{{t.id}}">{{t.name}}</option>
<!-- 循环显示分类标签 结束处 -->{% endfor %}
											<div class="clearfix"></div>						
										</select>
									</div>
									<div class="clearfix"></div>							
									<div class="subbox">
										<input id="subbox" type="checkbox" onclick="sub()" checked>我已阅读并同意排队网服务协议
									</div>
									<div>
										<div style="text-align:center;"><input id="subbutton3" type="submit" class="btn btn-info" value="创建悬赏"></div>
									</div>
								</div>
							</div>
<!-- 标签设置 结束处 -->

						</div>
					</form>
					</div>
				</div>
			</div>
<!-- 中间留白div -->

<!-- right div -->
			<div class="col-xs-4">
				<div class="agreement">
					在此处要告诉发布者 要在课程系列里面添加课时
				</div>
			</div>
		</div>
	</div>
	
	

</body>
</html>

templates/rewards/rewards.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>麦知网——学问有余，乐为人师</title>

<!-- Bootstrap core CSS -->
<link href="../../css/bootstrap.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="../../css/non-responsive.css" rel="stylesheet">
<link href="../../css/font-awesome.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<link href="../../css/rewards.css" rel="stylesheet">    

	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="../../js/jquery.min.js"></script>
	
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="../../js/bootstrap.js"></script>
	
	<script type="text/javascript">
		$(function(){
			array=[];
			//给每个大分类确定一个颜色， PUSH进ARRAY（有几个大分类就PUSH几个颜色）
			array.push("186,85,211");
			array.push("138,43,226");
			array.push("95,158,160");
			array.push("0,191,255");
			//有几个大分类就循环几次
			for(i=1;i<=4;i++){
				$("#a_type"+i).css("background-color","rgb("+array[i-1]+")");
			}
			
		})

		function changeOrder(typeid)
		{
			if(typeid){
				var sel=$("#sel").val();
				window.location.href="http://192.168.1.120:8866/rewards/rewards/?order="+sel+"&typeid="+typeid;
				
			}else{
				var typeid=$("#typeid").val();
				var sel=$("#sel").val();
				if(typeid){
					window.location.href="http://192.168.1.120:8866/rewards/rewards/?order="+sel+"&typeid="+typeid;
				}else{
					window.location.href="http://192.168.1.120:8866/rewards/rewards/?order="+sel;
				}
				
			}
		}

		function pageChange(page){
			var typeid=$("#typeid").val();
			alert(typeid);
			if(typeid){
				var sel=$("#sel").val();
				window.location.href="?page="+page+"&typeid="+typeid+"&order="+sel;
			}
		}
		
	</script>
</head>
<body>
	{% include 'public/common/header.html' %}
<div class="container" style="margin-top:45px">
	<div class="row">
<!-- 左侧div -->
		<div class="col-xs-4">
			<div>
				<a href="{% url 'rewards:rewardcreate' %}" type="button" class="btn btn-warning rewards_btn"><b>发布我的需求</b></a>
			</div>
			<div class="rewards_types">
				<div><h4>按分类检索</h4></div>
				<div>
<!-- 一个分类  循环开始处   div的id是大分类的id  需要确保id是连续的 -->
					{% for t in types %}
					<div id="a_type{{t.id}}" class="pull-left rewards_a_type">
						<a href="javascript:void(0)" onclick="changeOrder({{t.id}});" style="color:#ffffff;">{{t.name}}</a>
					</div>
					{% endfor %}
<!-- 一个分类  循环结束处 -->
					<div class="clearfix"></div>
					<div class="rewards_type_other"><a href=""><b>其他</b></a></div>				
				</div>
			</div>
			<div class="rewards_interest">
				<div><h4>您可能感兴趣的其他悬赏</h4></div>
				<div>
<!-- 您可能感兴趣的其他悬赏   一条 循环开始处 -->
					<div class="rewards_a_interest">
						<div class="rewards_inter_name pull-left">
							<a href="" title="哈哈我也想要PHP达内课程快给我快给我~！">哈哈我也想要PHP达内课程快给我快给我~！</a>
						</div>
						<div class="pull-right">
							￥25555.00
						</div>
						<div class="clearfix"></div>
					</div>
<!-- 您可能感兴趣的其他悬赏   一条 循环结束处 -->
				</div>
			</div>
		</div>
<!-- 右侧div -->
		<div class="col-xs-8">
			<div class="rewards_sel">
				<select id="sel" onchange="changeOrder();">
					<option value="1">按时间排列</option>
					{% ifequal order 2 %}
					<option value="2" selected>按人气排列</option>
					{% else %}
					<option value="2">按人气排列</option>
					{% endifequal %}
					{% ifequal order 3 %}
					<option value="3" selected>按价格由高到低排列</option>
					{% else %}
					<option value="3">按价格由高到低排列</option>
					{% endifequal %}
					{% ifequal order 4 %}
					<option value="4" selected>按价格由低到高排列</option>
					{% else %}
					<option value="4">按价格由低到高排列</option>
					{% endifequal %}
				</select>
			</div>
			<div class="all_rewards" id="all_rewards">
<!-- 一个悬赏 循环开始处 -->		{% for r in rewards %}								
				<div class="a_reward pull-left">
					<div class="a_a_reward">
						<div class="a_reward1">
							<div class="a_reward11 pull-left">
								<div class="reward_img"><img src="{{r.6}}/{{r.0}}" width="100%" class="img-circle"></div>
							</div>
							<div class="a_reward12 pull-left">
								<div class="reward_type pull-right"><b>#{{r.5}}</b></div>
								<div class="clearfix"></div>
								<div class="reward_name">
									{{r.2}}
								</div>
								<div class="reward_price"><b>￥{{r.3}}</b></div>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="a_reward2">
							<div class="topdirection"></div>
						</div>
						<div class="a_reward3">
							<div class="a_reward31">{{r.4}}</div>
							<div class="reward_in pull-right"><a href="{% url 'rewards:thereward' r.1 %}" target="_blank"><b>查看详情</b></a></div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
<!-- 一个悬赏 循环结束处 -->	{% endfor %}
				<div class="clearfix"></div>
			</div>

			<div>
					<ul class="pager">
					{% if rewards.has_previous %}
					  <li>
					  	<a href="javascript:void(0)" onclick="pageChange({{ rewards.previous_page_number }});">&larr;上一页</a>
					  </li>
					{% endif %}
					共 {{ rewards.number }} 页  第 {{ rewards.paginator.num_pages }} 页.
					{% if rewards.has_next %}
					  <li>
					  	<a href="javascript:void(0)" onclick="pageChange({{ rewards.next_page_number }});">下一页&rarr;</a>
					  </li>
					{% endif %}
						<form><input type="hidden" id="typeid" value="{{typeid}}"/></form>
					</ul>
			</div>				

			

		</div>
	</div>
</div>
	
	
	
	

</body>
</html>