groups/urls.py
from django.conf.urls import patterns, url
from groups import views

urlpatterns = patterns('',
    url(r'^$', views.groups, name="groups"),
    url(r'^the/download/down/$', views.down, name="down"),
    url(r'^the/download/del/$', views.delete, name="del"),
    url(r'^the/download/(.+)$', views.download, name="download"),
    url(r'^the/upload/(.+)$', views.upload, name="upload"),
    url(r'^the/(.+)$', views.thegroup, name="thegroup"),
    url(r'^change/$', views.change, name="change"),
    url(r'^join/$', views.join, name="join"),
    url(r'^topic/create/(.+)$', views.topiccreate, name="topiccreate"),
    url(r'^topic/publish/$', views.publish, name="publish"),
    url(r'^topic/collect/$', views.collect, name="collect"),
    url(r'^topic/comment/$', views.comment, name="comment"),
    url(r'^topic/cccomment/$', views.cccomment, name="cccomment"),
    url(r'^topic/good/$', views.good, name="good"),
    url(r'^topic/ban/$', views.ban, name="ban"),
    url(r'^topic/dt/$', views.deleteTopic, name="deleteTopic"),
    url(r'^topic/dr/$', views.deleteReview, name="deleteReview"),
    url(r'^topic/(.+)$', views.thetopic, name="thetopic"),
    url(r'^create/$', views.groupcreate, name="groupcreate"),

    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/css' } 
	),
	url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/fonts' } 
    ), 
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/templates/public/img' } 
    ), 
    url(r'^news/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/news' } 
    ), 
    url(r'^ico/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/ico' } 
    ), 
    url(r'^avatar/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/avatar/' } 
    ), 
    url(r'^group/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/image' } 
    ), 
    url(r'^file/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/file' } 
    ), 
)

mz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mz.views.home', name='home'),
    # url(r'^mz/', include('mz.foo.urls')),
    url(r'^',include('login.urls',namespace='login')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/',include('courses.urls',namespace='courses')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^rewards/',include('rewards.urls',namespace='rewards')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^publish/$', views.publish, name="publish"),
    url(r'^setting/$', views.setting, name="setting"),
    url(r'^good/$', views.good, name="good"),
    url(r'^cogood/$', views.cogood, name="cogood"),
    url(r'^get/$', views.getimg, name="get"),
    url(r'^add/$', views.add, name="add"),
    url(r'^share/$', views.share, name="share"),
    url(r'^setting/update/$', views.update, name="update"),
    url(r'^setting/pwdchange/$', views.pwdchange, name="pwdchange"),
    url(r'^setting/head/$', views.head, name="head"),
    url(r'^mycourse/$', views.mycourseact, name="mycourseact"),
    url(r'^home/(.+)$', views.home, name="home"),
    url(r'^message/$', views.message, name="message"),
    url(r'^manage/course/$', views.managecourse, name="managecourse"),
    url(r'^manage/group/$', views.managegroup, name="managegroup"),
    url(r'^manage/reward/$', views.managereward, name="managereward"),
    url(r'^mytopic/$', views.mytopic, name="mytopic"),
    url(r'^teacherapply/$', views.teacherapply, name="teacherapply"),
    url(r'^comment/$', views.comment, name="comment"),
    url(r'^cocomment/$', views.cocomment, name="cocomment"),
    url(r'^get_more_re/$', views.get_more_re, name="get_more_re"),
    
    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/css' } 
	),
	url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/fonts' } 
    ), 
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/img' } 
    ), 
    url(r'^news/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/news' } 
    ), 
    url(r'^ico/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/ico' } 
    ), 
    url(r'^group/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/image' } 
    ), 
)

groups/models.py
from django.db import models

class Group(models.Model):
	tag=models.CommaSeparatedIntegerField(max_length=99)
	topic_con=models.IntegerField(default=0)
	filespace=models.IntegerField(default=2097152)
	user_id=models.IntegerField()
	introduce=models.TextField()
	domain=models.CharField(max_length=99)
	img=models.ImageField(upload_to='templates/picture/group/image/',blank=True,null=True)
	name=models.CharField(max_length=99)
	crew_con=models.IntegerField(default=1)
	status=models.IntegerField(default=1)
	time=models.DateTimeField(auto_now_add=True)


class Topic(models.Model):
	group=models.ForeignKey(Group)
	user_id=models.IntegerField()
	share_con=models.IntegerField(default=0)
	collect_con=models.IntegerField(default=0)
	review_con=models.IntegerField(default=0)
	name=models.CharField(max_length=99)
	content=models.TextField()
	img=models.ImageField(upload_to='templates/picture/topic/',blank=True,null=True)
	time=models.DateTimeField(auto_now_add=True)
	last_time=models.DateTimeField(auto_now=True)

class Review_of_topic(models.Model):
	topic=models.ForeignKey(Topic)
	from_id=models.IntegerField()
	to=models.IntegerField(blank=True,null=True)
	content=models.TextField()
	good_con=models.IntegerField(default=0)
	review_con=models.IntegerField(default=0)
	to_review=models.IntegerField(blank=True,null=True)
	time=models.DateTimeField(auto_now_add=True)

class Good_review_of_topic(models.Model):
	review_of_topic=models.ForeignKey(Review_of_topic)
	user_id=models.IntegerField()

class Group_file(models.Model):
	group=models.ForeignKey(Group)
	user_id=models.IntegerField()
	name=models.CharField(max_length=99)
	introduce=models.TextField()
	file_path=models.FileField(upload_to='templates/picture/group/file/')
	down_con=models.IntegerField(default=0)
	file_length=models.CharField(max_length=50)
	time=models.DateTimeField(auto_now_add=True)

groups/views.py
#encoding:utf-8

from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import PageNotAnInteger, Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render
from users.models import Info,Follow_group,Message,Follow_topic,Follow_user
from groups.models import Group,Topic,Review_of_topic,Good_review_of_topic,Group_file
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt 
from PIL import Image
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import re,md5,os,time,json,qiniu.io,qiniu.conf,qiniu.rs,base64

class PutPolicy(object):
    scope = 'maizhi'         
    expires = 3600       
    callbackUrl = None
    callbackBody = None
    returnUrl = None
    returnBody = None
    endUser = None
    asyncOps = None

    def __init__(self, scope):
        self.scope = scope

qiniu.conf.ACCESS_KEY = "EW8idy4EFnJDBicDJZhPIVIVDU9AL0g4waW5MNtJ"
qiniu.conf.SECRET_KEY = "C1qaP_-sgjVgQb6GGHJ-vCle0qTiGI8qtbgOumOB"

def groups(request):
	info=Info.objects.get(user_id=request.session['id'])
	gro=Group.objects.all()
	follow=Follow_group.objects.filter(user_id=request.session['id'])
	fg=[]
	for f in follow:
		fg.append(int(f.follow_group_id))
	group=[]
	for i in gro:
		if i.user_id==request.session['id']:
			pass
		else:
			each=[]
			each.append(i.img)     #0  
			each.append(i.name)    #1
			if i.id in fg:
				join=True
				each.append('1')   #2
			else:
				join=None
				each.append('0')   #2
			each.append(i.id)      #3
			each.append(i.domain)  #4
			group.append(each)
	m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
	mess=[]
	for k in m:
		each=[]
		name=Info.objects.get(user_id=k.from_id).user_name
		content=k.content
		each.append(name)
		each.append(content)
		mess.append(each)
	havent=0
	for n in m:
		if n.status==1:
			havent+=1
	return render(request,'groups/groups.html',{'groups':group,'fg':fg,'message':mess,'havent':havent,'info':info})

def join(request):
	my=Follow_group.objects.filter(user_id=request.session['id'])
	group=Group.objects.get(id=request.GET['id'])
	follow=[]
	for i in my:
		follow.append(int(i.follow_group_id))
	if int(request.GET['id']) in follow:
		Follow_group.objects.filter(user_id=request.session['id']).get(follow_group_id=request.GET['id']).delete()
		crew_con=int(group.crew_con)-int(1)
		group.crew_con=crew_con
		group.save()
	else:
		Follow_group(user_id=request.session['id'],follow_group_id=request.GET['id'],status='1',topic_con='0',good_con='0',review_con='0',file_con='0').save()
		crew_con=int(group.crew_con)+int(1)
		group.crew_con=crew_con
		group.save()
	return HttpResponse('OK !')

def thegroup(request,id):
	group=Group.objects.get(id=id)
	if 'groupImg' in request.FILES:
		image=request.FILES['groupImg']
		pattern=re.compile(r'\.') 
		head=pattern.split(str(image))
		head[0]=group.name
		filename=head[0]+'.'+head[1]
		dirs ='templates/picture/group/image/'+filename
		content = image.read()
		if os.path.isfile(dirs):
			os.remove(dirs) 
		fp=open(dirs, 'wb')
		fp.write(content)
		fp.flush()
		fp.close()
		group.img=filename
		group.save()
	f=Follow_user.objects.filter(user_id=request.session['id'])
	follow=[]
	for  m in f:
		follow.append(m.follow_user_id)
	active=Follow_group.objects.filter(follow_group_id=group.id).order_by('-good_con')[0:5]
	actman=[]
	for act in active:
		if act.user_id in follow:
			pass
		elif act.user_id == request.session['id']:
			pass
		else:
			each=[]
			info=Info.objects.get(user_id=act.user_id)
			each.append(info.user_name)    #0
			each.append(info.img)          #1
			each.append(act.good_con)	   #2
			each.append(act.user_id)	   #3
			actman.append(each)
	if request.session['id']==group.user_id:
		status='1'
	else:
		f=Follow_group.objects.filter(user_id=request.session['id'])
		follow=[]
		for i in f:
			follow.append(i.follow_group_id)
		if group.id in follow:
			user=Follow_group.objects.filter(follow_group_id=group.id).get(user_id=request.session['id'])
			if int(user.status)==int(1):
				status='2'
			else:
				status='4'
		else:
			status='3'
	m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
	mess=[]
	for k in m:
		each=[]
		name=Info.objects.get(user_id=k.from_id).user_name
		content=k.content
		each.append(name)
		each.append(content)
		mess.append(each)
	havent=0
	for n in m:
		if n.status==1:
			havent+=1
	recommend=Topic.objects.filter(group_id=group.id).order_by('-review_con')[0:5]
	limit = 15
	topics=Topic.objects.filter(group_id=group.id).order_by('-last_time')
	paginator = Paginator(topics, limit)
	page = request.GET.get('page')
	try:
	    topics = paginator.page(page)
	except PageNotAnInteger:
	    topics = paginator.page(1)
	except EmptyPage:
	    topics = paginator.page(paginator.num_pages)
	topic=[]
	for k in topics:
		each=[]
		i=Info.objects.get(user_id=k.user_id)
		each.append(i.user_name)     #0
		each.append(k.name)          #1
		each.append(k.last_time)     #2
		each.append(k.review_con)    #3
		each.append(k.id)            #4
		each.append(k.user_id)       #5
		try:
			user=Follow_group.objects.filter(follow_group_id=group.id).get(user_id=k.user_id)
			each.append(user.status) #6
		except:
			each.append('3')         #6
		if k.user_id == group.user_id:
			each.append('1')         #7
		else:
			each.append('2')         #7
		topic.append(each)
	info=Info.objects.get(user_id=request.session['id'])
	return render(request,'groups/theGroup.html',{'info':info,'group':group,'status':status,'actman':actman,'message':mess,'havent':havent,'topic':topic,'topics':topics,'recommend':recommend})

def topiccreate(request,id):
	group=Group.objects.get(id=id)
	m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
	mess=[]
	for k in m:
		each=[]
		name=Info.objects.get(user_id=k.from_id).user_name
		content=k.content
		each.append(name)
		each.append(content)
		mess.append(each)
	havent=0
	for n in m:
		if n.status==1:
			havent+=1
	info=Info.objects.get(user_id=request.session['id'])
	return render(request,'groups/topicCreate.html',{'info':info,'group':group,'message':mess,'havent':havent})

@csrf_exempt
def publish(request):
	#try:
		policy = qiniu.rs.PutPolicy('mztopic')
		uptoken = policy.token()
		content=request.POST['editor'].replace('*','+')
		content=content.replace('}',';')
		image=re.findall("src=\"(.+?)\"",content)
		img=[]
		for i in image:
			st=time.time()
			dirs ='templates/picture/topic/'+str(st)
			if os.path.isfile(dirs):
				os.remove(dirs) 
			frd=str(i).split(',')
			decode=base64.decodestring(frd[1])
			f=open(dirs,'w')
			f.write(decode)
			f.close()
			ret=qiniu.io.put_file(uptoken,str(st),r"/home/tron/Maizhi/templates/picture/topic/"+str(st))
			if ret:
				os.remove(dirs)
			domain="http://mztopic.qiniudn.com/"
			img.append(domain+str(st))
		for j in img:
			start=content.find("src=\"data")
			start=int(start)+int(5)
			end=content.find("\"",start)
			end=int(end)
			content=content.replace(content[start:end],j)
		#tname=time.time()
		#dirs ='templates/topic/'+str(tname)
		#if os.path.isfile(dirs):
		#	os.remove(dirs) 
		#fp=open(dirs, 'wb')
		#fp.write(content)
		#fp.flush()
		#fp.close()
		topic=Topic(group_id=request.POST['group'],user_id=request.session['id'],name=request.POST['title'],content=content)
		topic.save()
		#return HttpResponse(content)
		return HttpResponse(int(topic.id))
	#except:
	#	return HttpResponse('Wrong')	

def thetopic(request,id):
	#try:
		topic=Topic.objects.get(id=id)
		user=Info.objects.get(user_id=topic.user_id)
		group=Group.objects.get(id=topic.group_id)
		m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
		mess=[]
		for k in m:
			each=[]
			name=Info.objects.get(user_id=k.from_id).user_name
			content=k.content
			each.append(name)
			each.append(content)
			mess.append(each)
		havent=0
		for n in m:
			if n.status==1:
				havent+=1
		competence=None
		if group.user_id==request.session['id']:
			competence=True
		recommend=Topic.objects.filter(group_id=group.id).order_by('-review_con')[0:5]
		c=Follow_topic.objects.filter(user_id=request.session['id'])
		collect=[]
		for j in c:
			collect.append(j.follow_topic_id)
		abord=None
		if topic.id in collect:
			abord=True
		limit = 15
		topics=Review_of_topic.objects.filter(topic_id=topic.id).order_by('-time')
		paginator = Paginator(topics, limit)
		page = request.GET.get('page')
		try:
		    topics = paginator.page(page)
		except PageNotAnInteger:
		    topics = paginator.page(1)
		except EmptyPage:
		    topics = paginator.page(paginator.num_pages)
		review=[]
		for r in topics:
			each=[]
			each.append(r.content)         	  	  #0
			each.append(r.time)                              	 #1
			each.append(r.good_con)                        #2
			each.append(r.review_con)                     #3
			info=Info.objects.get(user_id=r.from_id)
			each.append(info.user_name)                   #4
			each.append(info.img)                         #5
			each.append(r.id)                             #6
			each.append(info.domain)                             #7
			review.append(each)
		info=Info.objects.get(user_id=request.session['id'])
		return render(request,'groups/theTopic.html',{'info':info,'topic':topic,'user':user,'group':group,'message':mess,'havent':havent,'competence':competence,'recommend':recommend,'abord':abord,'review':review,'topics':topics})
	#except:
	#	return HttpResponse('404')

def good(request):
	entire=Good_review_of_topic.objects.filter(review_of_topic_id=request.GET['id'])
	for i in entire:
		if request.session['id']==i.user_id:
			return HttpResponse('2')
	Good_review_of_topic(review_of_topic_id=request.GET['id'],user_id=request.session['id']).save()
	review=Review_of_topic.objects.get(id=request.GET['id'])
	topic=Topic.objects.get(id=review.topic_id)
	n=Follow_group.objects.filter(user_id=request.session['id']).get(follow_group_id=topic.group_id)
	g=int(n.good_con)+int(1)
	n.good_con=g
	n.save()

templates/groups/download.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>麦知网——学问有余，乐为人师</title>

<!-- Bootstrap core CSS -->
<link href="../../css/bootstrap.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="../../css/non-responsive.css" rel="stylesheet">
<link href="../../css/font-awesome.min.css" rel="stylesheet">
<link href="../../css/download.css" rel="stylesheet">    
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="../../js/jquery.min.js"></script>
<script src="../../js/download.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="../../js/bootstrap.js"></script>
<script src="../../js/sco.message.js"></script>
<link href="../../css/sco.message.css" rel="stylesheet">
<link href="../../css/scojs.css" rel="stylesheet"> 
</head>
<body>
	{% include 'public/common/header.html' %}
	<div class="container" style="margin-top:45px">
		<div class="row">
			<div class="col-xs-12">
				<div class="dl_groupMes">
					<div class="pull-left group_img"><img src="{{group.domain}}/{{group.img}}" width="100%"/></div>
					<div class="pull-left group_name">
						<div class="group_nam"><b>{{group.name}}</b></div>
						<div class="return_group"><a href="{% url 'groups:thegroup' group.id %}"><span class="glyphicon glyphicon-arrow-left"></span> 返回小组</a></div>
					</div>
					<div class="pull-left group_space">
						<div class="dl_upload">
							<a href="{% url 'groups:upload' group.id %}" type="button" class="btn btn-warning">上传小组资源</a>
						</div>
						<div>剩余空间：{{free|floatformat}}MB  /  {{space|floatformat}}%</div>
						<div class="progress progress-striped dl_progress">
						  <div class="progress-bar progress-bar-info"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: {{space|floatformat}}%">
						    <span class="sr-only">{{space|floatformat}}% Complete</span>
						  </div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div>
					<table class="table table-hover">
						<thead>
							<tr>
								<th class="th1">上传者</th>
								<th class="th2">下载量</th>
								<th class="th3">上传时间</th>
								<th class="th4">文件</th>
								<th class="th5">文件介绍</th>
<!-- 只有发布者才有   开始处 -->
							{% if competence %}
								<th class="th6">管理</th>
							{% endif %}
<!-- 只有发布者才有    结束处-->
							</tr>
						</thead>
						<tbody>
<!-- 一个文件  循环开始处 -->
						{% for i in document %}
							<tr>
								<td>
									<div class="td_text"><a href="{% url 'users:home' i.1 %}">{{i.0}}</a></div>
								</td>
								<td>
									<div class="td_text" id="down_con{{i.7}}">{{i.2}}</div>
								</td>
								<td><div class="td_text">{{i.5|date:"Y-m-d H:i"}}</div></td>
								<td><div class="td_text"><a href="../../file/{{i.6}}" onclick="downloads({{i.7}})">{{i.3}}</a></div></td>
								<td>
									<div class="td_text2">{{i.4}}</div>
								</td>
<!-- 只有发布者才有   开始处 -->
							{% if competence %}
								<td>
									<div class="td_text">
										<span class="td_a"><a href="javascript:void(0)" onclick="del({{i.7}})">删除</a></span>
									</div>
								</td> 
							{% endif %}
<!-- 只有发布者才有  结束处 -->							
							</tr>
						{% endfor %}
<!-- 一个文件   循环结束处 -->
						</tbody>
					</table>
					<ul class="pager">
						{% if files.has_previous %}
						  <li><a href="?page={{ files.previous_page_number }}">&larr;上一页</a></li>
						{% endif %}
						共 {{ files.number }} 页  第 {{ files.paginator.num_pages }} 页.
						{% if files.has_next %}
						  <li><a href="?page={{ files.next_page_number }}">下一页&rarr;</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
	</div>

	
	
	

</body>
</html>

templates/groups/groups.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>麦知网——学问有余，乐为人师</title>

<!-- Bootstrap core CSS -->
<link href="../css/bootstrap.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="../css/non-responsive.css" rel="stylesheet">
<link href="../css/font-awesome.min.css" rel="stylesheet">
<link href="../css/bootstrap-switch.css" rel="stylesheet">
<link href="../ico/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
<link href="../css/groups.css" rel="stylesheet">    
 
</head>
<body>
	{% include 'public/common/header.html' %}
	<div class="container" style="margin-top:45px">
		<div class="row">
			<div class="col-xs-12">
<!-- 两个按钮 -->
				<div class="twoBtn">
					<a href="{% url 'groups:groupcreate' %}" type="button" class="btn btn-lg btn-primary">创建小组</a>
					<a href="{% url 'users:managegroup' %}" type="button" class="btn btn-lg btn-warning">我的小组</a>
				</div>
<!-- 所有小组 -->
				<div class="groups">
<!-- 一个小组 循环开始处 -->
					{% for i in groups %}					
					<div class="a_group pull-left">
						<div class="imgDiv"><img src="{{i.4}}/{{i.0}}" width="120px" class="img"></div>
						<div class="groupName"><a href="{% url 'groups:thegroup' i.3 %}"><strong>{{i.1}}</strong></a></div>
						<div class="switchDiv">
							<div class="switch switch-small" data-on="info" data-off="NO">
<!--如果是  未加入的小组 -->	{% ifequal i.2 '0' %}
								<input type="checkbox" checked="checked" id="join{{i.3}}" onchange="join({{i.3}})"/> 
<!--如果是  已加入的小组 -->	{% else %}
								<input type="checkbox" id="join{{i.3}}" onchange="join({{i.3}})" />
							{% endifequal %}
							</div>
						</div>
					</div>	
					{% endfor %}
<!-- 一个小组 循环结束处 -->	
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
	
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="../js/jquery.min.js"></script>
	
	<script src="../js/join.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="../js/bootstrap.js"></script>
	<script src="../js/bootstrap-switch.js"></script>
	
</body>
</html>