courses/urls.py
from django.conf.urls import patterns, url
from courses import views

urlpatterns = patterns('',
    url(r'^types/$', views.types, name="types"),
    url(r'^types/gettiny/$', views.gettiny, name="gettiny"),
    url(r'^course/lession/$', views.changes, name="getchangestiny"),
    url(r'^types/tiny/course/lession/add/(.+)$', views.addlession, name="addlession"),
    url(r'^types/tiny/course/purchase/(.+)$', views.purchase, name="purchase"),
    url(r'^types/tiny/course/buy/(.+)$', views.buy, name="buy"),
    url(r'^types/tiny/course/lession/finish/$', views.finish, name="finish"),
    url(r'^types/tiny/course/lession/comment/$', views.comment, name="comment"),
    url(r'^types/tiny/course/lession/collect/$', views.collect, name="collect"),
    url(r'^types/tiny/course/lession/update/(.+)$', views.update, name="update"),
    url(r'^types/tiny/course/lession/(.+)$', views.thecourse, name="thecourse"),
    url(r'^types/tiny/course/play/(.+)$', views.play, name="play"),
    url(r'^types/tiny/course/(.+)$', views.courselist, name="courselist"),
    url(r'^types/tiny/(.+)$', views.tinytypes, name="tinytypes"),
    url(r'^types/create$', views.coursecreate, name="coursecreate"),
    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/css' } 
    ),
    url(r'^course/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/course' } 
    ),
    url(r'^type/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/type' } 
    ),
    url(r'^tiny/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/tinyType' } 
    ),
    url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/fonts' } 
    ), 
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/templates/public/img' } 
    ), 
    url(r'^news/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/news' } 
    ), 
    url(r'^ico/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/ico' } 
    ), 
    url(r'^avatar/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/avatar/' } 
    ), 
    url(r'^group/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/image' } 
    ), 
    url(r'^file/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/file' } 
    ), 
    url(r'^player/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/Dropbox/mz/templates/public/player' } 
    ), 
)

mz/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mz.views.home', name='home'),
    # url(r'^mz/', include('mz.foo.urls')),
    url(r'^',include('login.urls',namespace='login')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/',include('courses.urls',namespace='courses')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^rewards/',include('rewards.urls',namespace='rewards')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^publish/$', views.publish, name="publish"),
    url(r'^setting/$', views.setting, name="setting"),
    url(r'^good/$', views.good, name="good"),
    url(r'^cogood/$', views.cogood, name="cogood"),
    url(r'^get/$', views.getimg, name="get"),
    url(r'^add/$', views.add, name="add"),
    url(r'^share/$', views.share, name="share"),
    url(r'^setting/update/$', views.update, name="update"),
    url(r'^setting/pwdchange/$', views.pwdchange, name="pwdchange"),
    url(r'^setting/head/$', views.head, name="head"),
    url(r'^mycourse/$', views.mycourseact, name="mycourseact"),
    url(r'^home/(.+)$', views.home, name="home"),
    url(r'^message/$', views.message, name="message"),
    url(r'^manage/course/$', views.managecourse, name="managecourse"),
    url(r'^manage/group/$', views.managegroup, name="managegroup"),
    url(r'^manage/reward/$', views.managereward, name="managereward"),
    url(r'^mytopic/$', views.mytopic, name="mytopic"),
    url(r'^teacherapply/$', views.teacherapply, name="teacherapply"),
    url(r'^comment/$', views.comment, name="comment"),
    url(r'^cocomment/$', views.cocomment, name="cocomment"),
    url(r'^get_more_re/$', views.get_more_re, name="get_more_re"),
    
    url(r'^css/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/css' } 
	),
	url(r'^js/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/js' } 
    ),
    url(r'^fonts/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/fonts' } 
    ), 
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/public/img' } 
    ), 
    url(r'^news/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/news' } 
    ), 
    url(r'^ico/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/ico' } 
    ), 
    url(r'^group/(?P<path>.*)$', 'django.views.static.serve', 
        { 'document_root': '/home/tron/mz/maizhi/templates/picture/group/image' } 
    ), 
)

courses/models.py
from django.db import models

class Types(models.Model):
	name=models.CharField(max_length=29)
	img=models.ImageField(upload_to='templates/picture/type/normal/')
	big_img=models.ImageField(upload_to='templates/picture/type/big/')

class Tiny_type(models.Model):
	types=models.ForeignKey(Types)
	name=models.CharField(max_length=29)
	introduce=models.TextField()
	img=models.ImageField(upload_to='templates/picture/type/big/')

class Course(models.Model):
	tiny_type=models.ForeignKey(Tiny_type)
	status=models.IntegerField()
	over=models.IntegerField()
	teacher_id=models.IntegerField()
	password=models.CharField(max_length=49,blank=True,null=True)
	name=models.CharField(max_length=49)
	domain=models.CharField(max_length=99)
	introduce=models.TextField()
	tag=models.CommaSeparatedIntegerField(max_length=99)
	price=models.FloatField()
	grade=models.IntegerField()
	grade_con=models.IntegerField(default=0)
	purchase_con=models.IntegerField(default=0)
	time=models.DateTimeField(auto_now_add=True)
	deadline=models.DateTimeField(auto_now_add=True)
	img=models.CharField(max_length=99)

class Lession(models.Model):
	course=models.ForeignKey(Course)
	lession_no=models.IntegerField()
	name=models.CharField(max_length=49)
	time=models.DateTimeField(auto_now_add=True)
	video=models.FileField(upload_to='templates/lession/video')
	doc=models.FileField(upload_to='templates/lession/doc')

class Course_comment(models.Model):
	course=models.ForeignKey(Course)
	content=models.TextField()
	user_id=models.IntegerField()
	time=models.DateTimeField(auto_now_add=True)
	grade=models.IntegerField()

courses/views.py
#encoding:utf-8

from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import PageNotAnInteger, Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import Http404
from courses.models import Types,Tiny_type,Course,Lession,Course_comment
from login.models import Register
from users.models import Info,Teacher,News,Review_of_news,Message,Follow_topic,Follow_user,Follow_group,Follow_course,Post_reward,Post_course,Purchase,Good_news,Good_review_of_news
from rewards.models import Reward,Uncover,Reward_mes
from django.utils import timezone 
from PIL import Image
from django.contrib import messages
import re,md5,os,time,qiniu.io,qiniu.conf,qiniu.rs,base64

class PutPolicy(object):
    scope = 'maizhi'         
    expires = 3600       
    callbackUrl = None
    callbackBody = None
    returnUrl = None
    returnBody = None
    endUser = None
    asyncOps = None

    def __init__(self, scope):
        self.scope = scope

qiniu.conf.ACCESS_KEY = "EW8idy4EFnJDBicDJZhPIVIVDU9AL0g4waW5MNtJ"
qiniu.conf.SECRET_KEY = "C1qaP_-sgjVgQb6GGHJ-vCle0qTiGI8qtbgOumOB"

def types(request):
	info=Info.objects.get(user_id=request.session['id'])
	types=Types.objects.all()
	m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
	mess=[]
	for k in m:
		each=[]
		name=Info.objects.get(user_id=k.from_id).user_name
		content=k.content
		each.append(name)
		each.append(content)
		mess.append(each)
	havent=0
	for n in m:
		if n.status==1:
			havent+=1
	course=Course.objects.all().order_by('-grade')[0:20]
	c=Follow_course.objects.filter(user_id=request.session['id'])
	follow=[]
	courses=[]
	for j in c:
		follow.append(j.follow_course_id)
	for i in course:
		if i.id in follow:
			pass
		else:
			each=[]
			each.append(i.domain)		#0
			each.append(i.img)		#1
			each.append(i.id)		#2
			each.append(i.name)		#3
			courses.append(each)
	return render(request,'courses/types.html',{'info':info,'message':mess,'havent':havent,'types':types,'courses1':courses[0:4],'courses1':courses[0:4],'courses2':courses[5:8],'courses3':courses[9:13]})

def tinytypes(request,ty):
	tiny=Tiny_type.objects.filter(types_id=int(ty))
	types=Types.objects.get(id=int(ty))
	info=Info.objects.get(user_id=request.session['id'])
	return render(request,'courses/tinyTypes.html',{'info':info,'tiny':tiny,'types':types})

def courselist(request,id):
	info=Info.objects.get(user_id=request.session['id'])
	course=Course.objects.filter(tiny_type_id=id).order_by('grade')
	tiny=Tiny_type.objects.get(id=id)
	types=Types.objects.get(id=tiny.types_id)
	m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
	mess=[]
	for k in m:
		each=[]
		name=Info.objects.get(user_id=k.from_id).user_name
		content=k.content
		each.append(name)
		each.append(content)
		mess.append(each)
	havent=0
	for n in m:
		if n.status==1:
			havent+=1
	limit = 10
	paginator = Paginator(course, limit)
	page = request.GET.get('page')
	try:
	    course = paginator.page(page)
	except PageNotAnInteger:
	    course = paginator.page(1)
	except EmptyPage:
	    course = paginator.page(paginator.num_pages)
	result=[]
	for i in course:
		each=[]
		each.append(i.img)			#0
		each.append(i.name)			#1
		each.append(i.introduce)	#2
		each.append(i.price)		#3
		k=Info.objects.get(user_id=i.teacher_id)
		each.append(k.user_name)	#4
		each.append(i.id) 			#5
		each.append(i.grade) 		#6
		each.append(i.grade_con)	#7
		each.append(i.purchase_con)	#8
		each.append(i.domain)		#9
		result.append(each)
	user=Info.objects.all().order_by('fan_con')
	users=Follow_user.objects.filter(user_id=request.session['id'])
	follow=[]
	recommend=[]
	for j in users:
		follow.append(j.follow_user_id)
	for u in user:
		if u.user_id in follow:
			pass
		else:
			each=[]
			each.append(u.user_name)		#0
			each.append(u.domain)		#1
			each.append(u.img)			#2
			each.append(u.sign)			#3
			each.append(u.id)			#4
			h=Info.objects.get(user_id=u.user_id)	
			each.append(h.id)			#5
			recommend.append(each)
	return render(request,'courses/courseList.html',{'info':info,'message':mess,'havent':havent,'course':course,'tiny':tiny,'types':types,'result':result,'user1':recommend[0:3],'user2':recommend[4:6]})

def coursecreate(request):
	try:
		tj=time.time()
		policy = qiniu.rs.PutPolicy('mzvideoimg')
		uptoken = policy.token()
		if 'picture' in request.FILES:
			pic=request.FILES['picture']
			suffix=pic.name.split('.')[-1]
			pic=Image.open(pic)
			coordinate=request.POST['coordinate'].split('*')
			region = (int(round(float(coordinate[0]))+1),int(coordinate[1]),int(coordinate[2]),int(coordinate[3]))
			#region=(0,0,100,100)
			cropImg = pic.crop(region)
			#cropImg=pic.thumbnail((int(coordinate[2]),int(coordinate[3])),Image.ANTIALIAS)
			cropImg.save(r"/home/tron/Maizhi/templates/picture/course/"+str(tj)+'.'+suffix)
			#pic.save("/home/tron/Maizhi/templates/picture/course/"+str(tj)+'.'+suffix,suffix)
			#dirs ='templates/picture/course/'+str(tj)
			#if os.path.isfile(dirs):
			#	os.remove(dirs) 
			#fp=open(dirs, 'wb')
			#content=pic.read()
			#fp.write(content)
			#fp.flush()
			#fp.close()
		domain='http://mzvideoimg.qiniudn.com'
		if 'method' in request.GET:
			reward=Reward.objects.get(id=base64.decodestring(request.GET['reward']))
			to=base64.decodestring(request.GET['to'])
			if int(request.session['id']) != int(base64.decodestring(request.GET['user'])):
				raise Http404
			course=Course(name=request.POST['name'],img=str(tj),domain=domain,introduce=request.POST['introduce'],tiny_type_id='',price=reward.price,status=0,over=0,teacher_id=request.session['id'],grade=0)
		else:
			course=Course(name=request.POST['name'],img=str(tj),domain=domain,introduce=request.POST['introduce'],tiny_type_id=request.POST['tiny'],price=request.POST['price'],status=0,over=0,teacher_id=request.session['id'],grade=0)
		course.save()
		qiniu.io.put_file(uptoken,str(tj),r"/home/tron/Maizhi/templates/picture/course/"+str(tj)+'.'+suffix)
		status=course.id
		Post_course(user_id=request.session['id'],post_course_id=course.id,status=1).save()
		return render(request,'courses/success.html',{'status':status})
		#return HttpResponse(str(int(round(float(coordinate[0]))+1))+"---"+str(int(coordinate[1]))+"---"+str(int(coordinate[2]))+"---"+str(int(coordinate[3])))
		#return HttpResponse(coordinate)
	except:
		m=Message.objects.filter(to=request.session['id']).order_by('-time')[0:5]
		info=Info.objects.get(user_id=request.session['id'])
		mess=[]
		for k in m:
			each=[]
			name=Info.objects.get(user_id=k.from_id).user_name
			content=k.content
			each.append(name)
			each.append(content)
			mess.append(each)
		havent=0
		for n in m:
			if n.status==1:
				havent+=1
		tag=Types.objects.all()
		mycourse=Course.objects.filter(teacher_id=request.session['id']).count()
		if 'method' in request.GET:
			reward=Reward.objects.get(id=base64.decodestring(request.GET['reward']))
			method='1'
			price=int(reward.price)
		else:
			method='0'
			price=''
		return render(request,'courses/courseCreate.html',{'message':mess,'havent':havent,'tag':tag,'info':info,'mycourse':mycourse,'method':method,'price':price})
	

def gettiny(request):
	alltiny=Tiny_type.objects.filter(types_id=request.GET['tiny'])
	tiny=[]
	for i in alltiny:
		tiny.append(i.name)
		tiny.append('*')
		tiny.append(i.id)
		tiny.append(',')
	tiny.pop()
	return HttpResponse(tiny)

def changes(request):
	try:
		course=Course.objects.get(id=request.GET['courseid'])
		if 'name' in request.GET:
			course.name=request.GET['name']
		elif 'intro' in request.GET:
			course.introduce=request.GET['intro']
		course.save()
		return HttpResponse('1')
	except:
		return HttpResponse('2')

def finish(request):
	course=Course.objects.get(id=request.GET['course'])
	course.over=1
	course.save()
	return HttpResponse('1')

def thecourse(request,id):
	info=Info.objects.get(user_id=request.session['id'])
	course=Course.objects.get(id=id)
	tiny=Tiny_type.objects.get(id=course.tiny_type_id)
	types=Types.objects.get(id=tiny.types_id)
	tinfo=Info.objects.get(user_id=course.teacher_id)
	f=Follow_user.objects.filter(user_id=request.session['id'])
	follow=[]
	for i in f:
		follow.append(i.follow_user_id)
	if request.session['id']==course.teacher_id:
		focus='3'
	elif course.teacher_id in follow:
		focus='1'
	else:
		focus='0'
	if course.teacher_id==request.session['id']:
		limit='1'
	else:
		user=Purchase.objects.filter(user_id=request.session['id']).filter(status=1)
		own=[]
		for u in user:
			own.append(u.purchase_id)
		if course.id in own:
			limit='2'
		else:
			nopay=Purchase.objects.filter(user_id=request.session['id']).filter(status=2)
			nopaid=[]
			for n in nopay:
				nopaid.append(purchase_id)
			if course.id in nopaid:
				limit='3'
			else:
				limit='4'
	comment=Course_comment.objects.filter(user_id=request.session['id']).filter(course_id=course.id)
	if comment:
		review='1'
	else:
		review='0'
	dis=Course_comment.objects.filter(course_id=course.id)
	discuss=[]
	for d in dis:
		each=[]
		i=Info.objects.get(user_id=d.user_id)
		each.append(i.user_name)      			 #0
		each.append(i.img)			 	 #1
		each.append(d.content)			 #2
		each.append(d.grade)				 #3
		each.append(d.time)				 #4
		each.append(d.id)				 #5
		each.append(i.domain)				 #6
		discuss.append(each)
	lessions=Lession.objects.filter(course_id=course.id)
	#messages.success(request, 'Hello world.')  
	statu=Register.objects.get(id=course.teacher_id)
	purview=''
	if int(statu.status)==int(2):
		purview='1'
	elif int(statu.status)==int(3):
		purview='2'
	fc=Follow_course.objects.filter(user_id=request.session['id']).filter(follow_course_id=course.id)
	collect=''
	if fc:
		collect='1'
	else:
		collect='2'
	return render(request,'courses/theCourse.html',{'info':info,'course':course,'tinfo':tinfo,'limit':limit,'tiny':tiny,'type':types,'focus':focus,'lession':lessions,'discuss':discuss,'review':review,'purview':purview,'collect':collect})

def purchase(request,id):

templates/courses/courseList.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>麦知网——学问有余，乐为人师</title>

<!-- Bootstrap core CSS -->
<link href="../../../css/bootstrap.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="../../../css/non-responsive.css" rel="stylesheet">
<link href="../../../css/font-awesome.min.css" rel="stylesheet">
<link href="../../../css/courseList.css" rel="stylesheet">    
 
</head>
<body>
	{% include 'public/common/header.html' %}
	<div class="container" style="margin-top:45px">
		<div class="row">
<!-- left div -->
			<div class="col-xs-9">
				<div>
					<div class="pull-left">
					<ol class="breadcrumb courseList_breadcrumb">
					  <li><a href="{% url 'courses:types' %}">课程系列</a></li>
					  <li><a href="{% url 'courses:tinytypes' types.id %}">{{types.name}}</a></li>
					  <li class="active">{{tiny.name}}</li>
					</ol>
				</div>
				<div class="selDiv pull-right">
					<select id="selectWay">   
				        <option value="1">按价格排列</option>   
				        <option value="2">按时间排列</option>   
				        <option value="3">按人气排列</option>   
				   	</select>  
				</div>
				<div class="clearfix"></div>
				</div>
<!-- 一个课程 循环开始处 -->
				{% for i in result %}
				<div class="cl_a_course">
					<div>
						<div class="pull-left cl_a_course_left">
							<img src="../../../course/{{i.0}}" width="100%"/>
						</div>
						<div class="pull-left cl_a_course_right">
							<div class="cl_a_course_right1">
								<div class="pull-left cl_course_name"><b>{{i.1}}</b></div>
								<div class="pull-left">
<!-- 用星星评价的地方    第一个span是黄色星星  第二个span是空心星星  分别循环   -->
									<span class="yellow_star">&#9733</span><span class="yellow_star">&#9733</span><span class="yellow_star">&#9733</span><span class="yellow_star">&#9733</span><span>☆</span>
<!-- 用星星评价的地方 结束 -->							
								</div>
								<div class="pull-left cl_font">（{{i.7}}人评价）</div>
								<div class="pull-left cl_font">{{i.8}}人购买</div>
								<div class="pull-right"><span class="badge">￥{{i.3}}</span></div>
								<div class="clearfix"></div>
							</div>
							<div class="cl_intro"><i>
								{{i.2}}
							</i></div>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="a_course_bottom">
						<div class="pull-left a_course_bottom1">讲师：<b>{{i.4}}</b></div>
						<div class="pull-right a_course_bottom2"><a href="{% url 'courses:thecourse' i.5 %}">点击查看</a></div>
						<div class="clearfix"></div>
					</div>
				</div>
				{% endfor %}
<!-- 一个课程 循环结束处 -->
				<div class="clearfix"></div>
				<ul class="pager">
				{% if course.has_previous %}
					  <li><a href="?page={{ course.previous_page_number }}">&larr;上一页</a></li>
					{% endif %}
					共 {{ course.number }} 页  第 {{ course.paginator.num_pages }} 页.
					{% if course.has_next %}
					  <li><a href="?page={{ course.next_page_number }}">下一页&rarr;</a></li>
				{% endif %}
				</ul>
			</div>

<!-- right div -->
			<div class="col-xs-3">
				<div><img src="../../../img/lucky.png" width="100%"/></div>
				<div class="hot_newpage"><a href=""><span class="glyphicon glyphicon-globe"></span> 热门推荐</a></div>
<!-- 推荐 -->
				<div class="my">
					<div class="my_title"><b>推荐</b></div>
					<div class="pageChange">
						<span><button type="button" class="btn btn-default btn-xs" onclick="frontPage()"><</button></span>
						<span><button type="button" class="btn btn-default btn-xs" onclick="nextPage()">></button></span>
					</div>
<!-- 前五个推荐 循环开始处 -->
					<div class="a_guy">
						<div class="pull-left person_avatar"><a href=""><img src="../../../img/rd.jpg" width="100%"/></a></div>
						<div class="pull-left person_content">
							<div><span class="person_name"><a href=""><b>芸豆炖白菜孙芋头孙芋头</b></a></span></div>
							<div class="show_person">2222个共同好友</div>
							<div class="show_person">
								<span><a href="">点击查看</a></span>
								<span class="btn_friend"><button type="button" class="btn btn-info btn-xs">+好友</button></span>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
<!-- 前五个推荐 循环结束处 -->
<!-- 所有20（id为a0到a19）个推荐 循环开始处 -->
					<div id="a0" class="a_guy" style="display:none;">
						<div class="pull-left person_avatar"><a href=""><img src="../../../img/rd.jpg" width="100%"/></a></div>
						<div class="pull-left person_content">
							<div><span class="person_name"><a href=""><b>PHP</b></a></span></div>
							<div class="show_person"><a href="">点击查看</a></div>
						</div>
						<div class="clearfix"></div>
					</div>
<!-- 所有20个推荐  循环结束处 -->
				</div>
<!-- 推荐 结束处-->
			</div>
		</div>
	</div>
	
	
	
	
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="../../../js/jquery.min.js"></script>
	
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="../../../js/bootstrap.js"></script>
	
	<script type="text/javascript">
	var start_id_num=0;
		function frontPage()
		{	if(start_id_num > 0)
			{
				start_id_num-=5;alert(start_id_num);
				$(".a_guy").css("display","none");
				$("#a"+start_id_num).css("display","block");
				$("#a"+(start_id_num+1)).css("display","block");
				$("#a"+(start_id_num+2)).css("display","block");
				$("#a"+(start_id_num+3)).css("display","block");
				$("#a"+(start_id_num+4)).css("display","block");
			}
		}
		function nextPage()
		{
			if(start_id_num < 20)
			{
				start_id_num+=5;alert(+start_id_num);
				$(".a_guy").css("display","none");
				$("#a"+start_id_num).css("display","block");
				$("#a"+(start_id_num+1)).css("display","block");
				$("#a"+(start_id_num+2)).css("display","block");
				$("#a"+(start_id_num+3)).css("display","block");
				$("#a"+(start_id_num+4)).css("display","block");
			}
		
		}
		
		
	</script>
</body>
</html>

templates/courses/wait.html
<html>

<head>
<meta charset='utf-8'>
<script>
	window.onload=function() {
		window.location="http://192.168.1.113:8866/courses/types/tiny/course/lession/{{id}}"
	}
</script>
</head>

<body>
正在跳转....
</body>
</html>